name: Lint and Build Code Base

on:
  push:
    branches: [dev, main]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main, dev, release-*]
  workflow_dispatch:

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.js', '**.jsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
            
      - name: Install Dependencies
        run: npm ci

      - name: Lint (Check against Eslint rules for code quality)
        run: npm run lint
      - name: Prettier (Code style check)
        run: npm run prettier
      - name: All went well!
        run: echo Success
    env:
      CI: true
  
  build:
    name: Build Code Base
    runs-on: ubuntu-latest
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
    needs: [lint]
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
            
      - name: Install Dependencies
        run: npm ci
      - name: Build Dependencies
        run: npm run build
        env:
          NODE_ENV: production
          NEXT_TELEMETRY_DEBUG: 1
